### ISSUE TITLE
[Feature Request] Option to Round Top Corner

### ISSUE THREAD

**Issue by dorkbuttt** [aminought/firefox-second-sidebar#77]
Is it possible to have an option to add matching corner rounding where the page meets the browser?

<img width="1302" alt="A screenshot of the top of my Firefox Nightly installation showcasing the browser in vertical tabs mode. There is a clear distinction between the web browser and site, delineated by a change in color (white of the Github page with translucent greens and blues for the browser). However, running along the top edge of this delineation reveals a rounded corner on the left, but not one on the right." src="https://github.com/user-attachments/assets/ae4ec65e-d7cb-4f27-9911-f770d5e82d67" />

**Comment by aminought** [comment]
I don't think that this script should perform this action. I have a separate userChrome.css to round all corners.

**Comment by dorkbuttt** [comment]
@aminought How would one go about doing that? Will I have to parse through the userChrome.css file for the proper part of the sidebar it ultimately uses? Or is it possible to have that option uploaded somewhere? In either case we could close up this issue and I can stop being a pest.

**Comment by aminought** [comment]
I use something like that. There is not only rounding or corners but some extra spacing for the second sidebar.
```css
:root:not([sizemode="fullscreen"]) {
  #browser {
    background-color: var(--toolbar-bgcolor) !important;
  }

  #tabbrowser-tabbox {
    border-radius: var(--border-radius-medium) !important;
    height: calc(100% - var(--space-small));
    overflow: hidden !important;
  }

  #tabbrowser-tabpanels {
    clip-path: inset(0 0 round var(--border-radius-medium)) !important;
  }

  #sb2-box:has(#sb2[pinned="true"]) {
    padding-block-end: var(--space-small) !important;
  }

  #sb2-box:has(#sb2[pinned="false"]) {
    height: calc(100% - var(--sb2-box-unpinned-top-padding) - var(--sb2-box-unpinned-bottom-padding) - var(--space-small)) !important;
  }
}
```
